# .deepsource.toml

# The version of the configuration file format.
version = 1

# Define the analyzers for each language.
[[analyzers]]
name = "python"
enabled = true
version = "3.11"
dependency_file_paths = ["requirements.txt", "requirements-docs.txt"]

[[analyzers]]
name = "javascript"
enabled = true
# Specify the version of JavaScript.
# Default is 'es2018'.
version = "es2022"

[[analyzers]]
name = "secrets"
enabled = true
# This analyzer detects hardcoded secrets like API keys and passwords.

[[analyzers]]
name = "shell"
enabled = true
# This analyzer checks for common issues in shell scripts.

[[analyzers]]
name = "docker"
enabled = true
# This analyzer checks for security and best practices in Dockerfiles.

# You can configure specific analyzers.
# For example, to enable a specific linter rule for Python:
# [[analyzers.meta]]
# name = "flake8"
# enable_all = true

# You can also set a minimum severity for issues that will be reported.
# severity_threshold = "critical"
# Possible values: "critical", "major", "minor", "info"

# Configure transformers.
# Transformers are used to generate code before analysis.
# For example, if you use a build step that generates files.
# [[transformers]]
# name = "mypy"
# enabled = true

[[transformers]]
name = "black"
enabled = true

# To identify test files.
test_patterns = ["packages/cfsite/test/**/*.spec.js"]

# To ignore files or paths from being analyzed.
exclude_patterns = ["**/node_modules/", "_site/"]
