name: ğŸƒğŸ¼ Run pre-commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  pre-commit:
    name: ğŸƒğŸ¼ Pre-commit on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12", "3.11", "3.10"]
        exclude:
          - os: macos-latest
            python-version: "3.10"

    steps:
      - name: ğŸ Fix macOS gettext issue
        if: runner.os == 'macOS'
        run: |
          brew install gettext
          brew link --force gettext

      - name: Install dprint CLI
        if: runner.os != 'Windows'
        run: |
          curl -fsSL https://dprint.dev/install.sh | sh
          sudo mv ~/.dprint/bin/dprint /usr/local/bin/

      - name: Install dprint CLI on Windows
        if: runner.os == 'Windows'
        run: |
          iwr https://dprint.dev/install.ps1 -UseBasicParsing | iex
          move ~\.dprint\bin\dprint.exe C:\tools\dprint.exe
          setx PATH "$env:PATH;C:\tools"

      - name: â†©ï¸ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”§ Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"

      - name: ğŸª› Set PY (Python version hash)
        shell: bash
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> "$GITHUB_ENV"

      - name: ğŸ’¾ Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ runner.os }}|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: ğŸ’¾ Cache pip downloads
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip|${{ runner.os }}|${{ env.PY }}|${{ hashFiles('**/requirements*.txt', '.pre-commit-config.yaml') }}

      - name: ğŸª› Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: ğŸƒğŸ»â€â™‚ï¸â€â¡ï¸ Run pre-commit
        run: pre-commit run --all-files
